local M = {}

function M.get(c, opts)
  -- stylua: ignore  
	return {
    Foo                         = { bg = c.blue, fg = c.fg },

    Comment                     = { fg = c.green_5, italic = opts.styles.comments.italic, bold = opts.styles.comments.bold },
    ColorColumn                 = { bg = c.bg_float },
    Conceal                     = { fg = c.green_5 },
    Cursor                      = { fg = c.bg, bg = c.fg },
    lCursor                     = { fg = c.bg, bg = c.fg },
    CursorIM                    = { fg = c.bg, bg = c.fg },
    CursorColumn                = { bg = c.cursorline },
    CursorLine                  = { bg = c.cursorline },
    Directory                   = { fg = c.green_3 },
    DiffAdd                     = { bg = c.diff.add },
    DiffChange                  = { bg = c.diff.change },
    DiffDelete                  = { bg = c.diff.delete },
    DiffText                    = { bg = c.bg_visual },
    EndOfBuffer                 = { fg = c.bg },
    ErrorMsg                    = { fg = c.red },
    VertSplit                   = { fg = c.separator },
    WinSeparator                = { fg = c.separator, bold = true },
    Folded                      = { fg = c.gray, bg = c.bg_visual },
    FoldColumn                  = { bg = opts.transparent and c.none or c.bg, fg = c.green_5 },
    SignColumn                  = { bg = opts.transparent and c.none or c.bg, fg = c.green_5 },
    SignColumnSB                = { fg = c.green_5 },
    Substitute                  = { bg = c.red, fg = c.bg },
    LineNr                      = { fg = c.number },
    CursorLineNr                = { bg = opts.transparent and c.none or c.bg, fg = c.yellow, bold = true },
    LineNrAbove                 = "LineNr",
    LineNrBelow                 = "LineNr",
    MatchParen                  = { fg = c.red, bold = true },
    ModeMsg                     = { fg = c.fg, bold = true },
    MsgArea                     = { fg = c.gray },
    MoreMsg                     = { fg = c.blue },
    NonText                     = { fg = c.green_5 },
    Normal                      = { fg = c.fg, bg = opts.transparent and c.none or c.bg },
    NormalNC                    = { fg = c.fg, bg = opts.transparent and c.none or c.bg },
    NormalSB                    = { fg = c.fg, bg = c.bg },
    NormalFloat                 = { fg = c.fg, bg = c.bg_float },
    FloatBorder                 = { fg = c.green_3, bg = c.bg_float },
    FloatTitle                  = { fg = c.green_3, bg = c.bg_float },
    Pmenu                       = { bg = c.bg_float, fg = c.fg },
    PmenuBorder                 = { fg = c.green_3, bg = c.bg_float },
    PmenuMatch                  = { bg = c.bg_float, fg = c.green_2, bold = true },
    PmenuSel                    = { bg = c.bg_visual, bold = true },
    PmenuMatchSel               = { bg = c.cursorline },
    PmenuSbar                   = { bg = c.separator },
    PmenuThumb                  = { bg = c.bg_visual },
    PmenuExtra                  = { fg = c.green_5 },
    Question                    = { fg = c.blue },
    QuickFixLine                = { bg = c.bg_visual, bold = true },
    Search                      = { bg = c.green_3, fg = c.bg },
    IncSearch                   = { bg = c.orange, fg = c.bg },
    CurSearch                   =  "IncSearch",
    SpecialKey                  = { fg = c.green_4 },
    SpellBad                    = { sp = c.red, underline = true },
    SpellCap                    = { sp = c.yellow, underline = true },
    SpellLocal                  = { sp = c.yellow, underline = true },
    SpellRare                   = { sp = c.blue, underline = true },
    StatusLine                  = { fg = c.fg, bg = c.statusbar.bg },
    StatusLineNC                = { fg = c.gray, bg = c.bg },
    TabLine                     = { bg = c.statusbar.bg, fg = c.green_5 },
    TabLineFill                 = { bg = opts.transparent and c.none or c.statusbar.bg, fg = c.green_3 },
    TabLineSel                  = { fg = c.bg, bg = c.green_2 },
    Title                       = { fg = c.green_2, bold = true },
    Visual                      = { bg = c.bg_visual },
    VisualNOS                   = { bg = c.bg_visual },
    WarningMsg                  = { fg = c.yellow },
    Whitespace                  = { fg = c.fg },
    WildMenu                    = { bg = c.bg_visual },
    WinBar                      = "StatusLine",
    WinBarNC                    = "StatusLineNC",

    Bold                        = { bold = true, fg = c.fg },
    Character                   = { fg = c.green_3 },
    Constant                    = { fg = c.yellow },
    Debug                       = { fg = c.orange },
    Delimiter                   = { fg = c.green_0 },
    Error                       = { fg = c.red },
    Function                    = { fg = c.blue },
    Identifier                  = { fg = c.green_0 },
    Italic                      = { italic = true, fg = c.fg },
    Include                     = "Keyword",
    Keyword                     = { fg = c.orange, italic = opts.styles.keywords.italic, bold = opts.styles.keywords.bold },
    Operator                    = { fg = c.red },
    PreProc                     = { fg = c.green_1 },
    Special                     = { fg = c.green_1 },
    Statement                   = { fg = c.orange },
    String                      = { fg = c.green_3, italic = opts.styles.strings.italic, bold = opts.styles.strings.bold }, -- left off here
    Todo                        = { bg = c.yellow, fg = c.bg },
    Type                        = { fg = c.green_2 },
    Underlined                  = { underline = true },
    debugBreakpoint             = { bg = c.red },
    debugPC                     = { bg = c.bg_float },
    dosIniLabel                 = "@property",
    helpCommand                 = { bg = c.separator, fg = c.blue },
    htmlH1                      = { fg = c.blue, bold = true },
    htmlH2                      = { fg = c.blue, bold = true },
    qfFileName                  = { fg = c.blue },
    qfLineNr                    = { fg = c.number },

    TreesitterContextLineNumber = { fg = c.number, bg = c.bg_float },

    LspReferenceText            = { bg = c.bg_visual, bold = true },
    LspReferenceRead            = { bg = c.bg_visual, bold = true },
    LspReferenceWrite           = { bg = c.bg_visual, bold = true },
    LspSignatureActiveParameter = { bg = c.bg_visual, bold = true },
    LspCodeLens                 = { fg = c.green_5 },
    LspInlayHint                = { fg = c.number, bg = c.none, italic = true },
    LspInfoBorder               = { fg = c.green_3, bg = c.bg_float },
    ComplHint                   = { fg = c.bg_float },


    DiagnosticError             = { fg = c.red },
    DiagnosticWarn              = { fg = c.yellow },
    DiagnosticInfo              = { fg = c.green_1 },
    DiagnosticHint              = { fg = c.blue },
    DiagnosticUnnecessary       = { fg = c.green_5 },
    DiagnosticVirtualTextError  = { fg = c.red },
    DiagnosticVirtualTextWarn   = { fg = c.yellow },
    DiagnosticVirtualTextInfo   = { fg = c.green_1 },
    DiagnosticVirtualTextHint   = { fg = c.blue },

    DiagnosticUnderlineError    = {
      underline = opts.styles.diagnostic.underline,
      undercurl = not opts.styles.diagnostic.underline,
      sp = c.red,
      fg = opts.styles.diagnostic.error.highlight and c.bg or c.red,
      bg = opts.styles.diagnostic.error.highlight and c.red or c.none,
    },
    DiagnosticUnderlineWarn     = {
      underline = opts.styles.diagnostic.underline,
      undercurl = not opts.styles.diagnostic.underline,
      sp = c.yellow,
      fg = opts.styles.diagnostic.warn.highlight and c.bg or c.yellow,
      bg = opts.styles.diagnostic.warn.highlight and c.yellow or c.none,
    },
    DiagnosticUnderlineInfo     = {
      underline = opts.styles.diagnostic.underline,
      undercurl = not opts.styles.diagnostic.underline,
      sp = c.green_6,
      fg = opts.styles.diagnostic.info.highlight and c.bg or c.green_2,
      bg = opts.styles.diagnostic.info.highlight and c.green_2 or c.none,
    },
    DiagnosticUnderlineHint     = {
      underline = opts.styles.diagnostic.underline,
      undercurl = not opts.styles.diagnostic.underline,
      sp = c.blue,
      fg = opts.styles.diagnostic.hint.highlight and c.bg or c.blue,
      bg = opts.styles.diagnostic.hint.highlight and c.blue or c.none,
    },


    healthError                 = { fg = c.red },
    healthSuccess               = { fg = c.green_1 },
    healthWarning               = { fg = c.yellow },


    diffAdded                   = { bg = c.diff.add, fg = c.git.add },
    diffRemoved                 = { bg = c.diff.delete, fg = c.git.delete },
    diffChanged                 = { bg = c.diff.change, fg = c.git.change },
    diffOldFile                 = { bg = c.blue, fg = c.fg },
    diffNewFile                 = { bg = c.green_1, fg = c.fg },
    diffFile                    = { fg = c.blue },
    diffLine                    = { fg = c.green_5 },
    diffIndexLine               = { fg = c.blue },
    helpExample                 = { fg = c.green_5 },
	}
end

return M
