# vim:set ft=tmux:

set -g @thorn_bg        "#131F20"
set -g @thorn_fg        "#DBD2C7"

set -g @thorn_status_bg "#9EC59B"
set -g @thorn_dim  "#0B1213"
set -g @thorn_inactive    "#233935"
set -g @thorn_visual    "#233935"

set -g @thorn_green_0   "#B8CDB6"
set -g @thorn_green_1   "#9EBB9C"
set -g @thorn_green_2   "#88B497"
set -g @thorn_green_3   "#9EC59B"
set -g @thorn_green_4   "#6FA791"
set -g @thorn_green_5   "#568270"
set -g @thorn_green_6   "#87CBB1"
set -g @thorn_yellow    "#FFD7AA"
set -g @thorn_orange    "#F2A597"
set -g @thorn_blue      "#91C4C0"
set -g @thorn_red       "#D2696C"

set -g @thorn_sep_right  ""
set -g @thorn_sep_left  ""
set -g @thorn_line_right  "╲"
set -g @thorn_line_left  "╱"

set -g pane-border-style fg='#{@thorn_dim}'
set -g pane-border-lines heavy
set -g pane-active-border-style fg='#{@thorn_green_3}'

set -g display-panes-colour "#568270"
set -g display-panes-active-colour "#FFD7AA"

set -g message-style "bg=#{@thorn_blue},fg=#{@thorn_bg}"

set -g clock-mode-colour "#9EC59B"
set -g clock-mode-style 12

set -g mode-style "bg=#{@thorn_green_2},fg=#{@thorn_bg}"

set -g copy-mode-match-style "bg=#{@thorn_green_3},fg=#{@thorn_bg}"
set -g copy-mode-current-match-style "bg=#{@thorn_orange},fg=#{@thorn_bg},bold"
set -g copy-mode-selection-style "bg=#{@thorn_visual}"

set -g status-style "bg=#{@thorn_bg},fg=#{@thorn_fg}"

set -g status-left-style none
set -g status-left-length 60
set -g status-left "#[bg=#{@thorn_green_3},fg=#{@thorn_bg},bold] #(whoami)@#h #[bg=#{@thorn_inactive},fg=#{@thorn_green_3}]#{@thorn_sep_right} #[bg=#{@thorn_inactive},fg=#{@thorn_green_3}]#S #[bg=#{@thorn_bg},fg=#{@thorn_inactive}]#{@thorn_sep_right}"

set -g status-right-style none
set -g status-right-length 60
set -g status-right "#[bg=#{@thorn_bg},fg=#{@thorn_inactive}]#{@thorn_sep_left}#[bg=#{@thorn_inactive},fg=#{@thorn_green_3}] %l:%M %p #[bg=#{@thorn_inactive},fg=#{@thorn_green_3}]#{@thorn_sep_left}#[bg=#{@thorn_green_3},fg=#{@thorn_bg},bold] %Y-%m-%d "

set -g window-status-separator ""
set -g window-status-format "#[bg=#{@thorn_bg},fg=#{@thorn_inactive}]#[bg=#{@thorn_inactive},fg=#{@thorn_green_3}] #I #{@thorn_line_right} #W #[bg=#{@thorn_bg},fg=#{@thorn_inactive}]#{@thorn_sep_right}"
set -g window-status-current-format "#[bg=#{@thorn_bg},fg=#{@thorn_green_2}]#[bg=#{@thorn_green_2},fg=#{@thorn_bg},bold] #I #{@thorn_line_right} #W #[bg=#{@thorn_bg},fg=#{@thorn_green_2}]#{@thorn_sep_right}"

