# vim:set ft=tmux:

set -g @thorn_bg        "#EFF5BD"
set -g @thorn_fg        "#3D4A2B"

set -g @thorn_status_bg "#3C6746"
set -g @thorn_dim  "#585A3F"
set -g @thorn_inactive    "#CFD69E"
set -g @thorn_visual    "#D8E4AF"

set -g @thorn_green_0   "#798656"
set -g @thorn_green_1   "#8DAE5A"
set -g @thorn_green_2   "#6E9948"
set -g @thorn_green_3   "#92AC3F"
set -g @thorn_green_4   "#516F21"
set -g @thorn_green_5   "#A3A776"
set -g @thorn_green_6   "#0D9039"
set -g @thorn_yellow    "#DCA838"
set -g @thorn_orange    "#CF7859"
set -g @thorn_blue      "#4C8A80"
set -g @thorn_red       "#C5524D"

set -g @thorn_sep_right  ""
set -g @thorn_sep_left  ""
set -g @thorn_line_right  "╲"
set -g @thorn_line_left  "╱"

set -g pane-border-style fg='#{@thorn_dim}'
set -g pane-border-lines heavy
set -g pane-active-border-style fg='#{@thorn_green_3}'

set -g display-panes-colour "#A3A776"
set -g display-panes-active-colour "#DCA838"

set -g message-style "bg=#{@thorn_blue},fg=#{@thorn_bg}"

set -g clock-mode-colour "#92AC3F"
set -g clock-mode-style 12

set -g mode-style "bg=#{@thorn_green_2},fg=#{@thorn_bg}"

set -g copy-mode-match-style "bg=#{@thorn_green_3},fg=#{@thorn_bg}"
set -g copy-mode-current-match-style "bg=#{@thorn_orange},fg=#{@thorn_bg},bold"
set -g copy-mode-selection-style "bg=#{@thorn_visual}"

set -g status-style "bg=#{@thorn_bg},fg=#{@thorn_fg}"

set -g status-left-style none
set -g status-left-length 60
set -g status-left "#[bg=#{@thorn_status_bg},fg=#{@thorn_bg},bold] #(whoami)@#h #[bg=#{@thorn_inactive},fg=#{@thorn_status_bg}]#{@thorn_sep_right} #[bg=#{@thorn_inactive},fg=#{@thorn_status_bg}]#S #[bg=#{@thorn_bg},fg=#{@thorn_inactive}]#{@thorn_sep_right}"

set -g status-right-style none
set -g status-right-length 60
set -g status-right "#[bg=#{@thorn_bg},fg=#{@thorn_inactive}]#{@thorn_sep_left}#[bg=#{@thorn_inactive},fg=#{@thorn_status_bg}] %l:%M %p #[bg=#{@thorn_inactive},fg=#{@thorn_status_bg}]#{@thorn_sep_left}#[bg=#{@thorn_status_bg},fg=#{@thorn_bg},bold] %Y-%m-%d "

set -g window-status-separator ""
set -g window-status-format "#[bg=#{@thorn_bg},fg=#{@thorn_inactive}]#[bg=#{@thorn_inactive},fg=#{@thorn_status_bg}] #I #{@thorn_line_right} #W #[bg=#{@thorn_bg},fg=#{@thorn_inactive}]#{@thorn_sep_right}"
set -g window-status-current-format "#[bg=#{@thorn_bg},fg=#{@thorn_green_2}]#[bg=#{@thorn_green_2},fg=#{@thorn_bg},bold] #I #{@thorn_line_right} #W #[bg=#{@thorn_bg},fg=#{@thorn_green_2}]#{@thorn_sep_right}"

